<a href="https://colab.research.google.com/github/Grinder7/GoogleColab/blob/main/Session%202/Pertemuan2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [16]:
help(np.sum)

Help on function sum in module numpy:

sum(a, axis=None, dtype=None, out=None, keepdims=<no value>, initial=<no value>, where=<no value>)
    Sum of array elements over a given axis.
    
    Parameters
    ----------
    a : array_like
        Elements to sum.
    axis : None or int or tuple of ints, optional
        Axis or axes along which a sum is performed.  The default,
        axis=None, will sum all of the elements of the input array.  If
        axis is negative it counts from the last to the first axis.
    
        .. versionadded:: 1.7.0
    
        If axis is a tuple of ints, a sum is performed on all of the axes
        specified in the tuple instead of a single axis or all the axes as
        before.
    dtype : dtype, optional
        The type of the returned array and of the accumulator in which the
        elements are summed.  The dtype of `a` is used by default unless `a`
        has an integer dtype of less precision than the default platform
        integer.  In 

In [5]:
# ALL

# a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]
a = np.array([[8, 3, -3], [-2, -8, 5], [3, 5, 10]])
diag = np.diag(np.abs(a))
off_diag = np.sum(np.abs(a), axis = 1) - diag
print(f'a = \n {a}')
print(f'diag = \n {diag}')
print(f'off_diag = \b {off_diag}')


a = 
 [[ 8  3 -3]
 [-2 -8  5]
 [ 3  5 10]]
diag = 
 [ 8  8 10]
off_diag =  [6 7 8]


Per Line

In [14]:
# a = [[8, 3, -3], [-2, -8, 5], [3, 5, 10]]
a = np.array([[8, 3, -3], [-2, -8, 5], [3, 5, 10]])
print(a)

[[ 8  3 -3]
 [-2 -8  5]
 [ 3  5 10]]


In [11]:
diag = np.diag(np.abs(a))
print(diag)

[ 8  8 10]


In [19]:
off_diag = np.sum(np.abs(a), axis = 1) - diag
# test1 = np.sum(np.abs(a), axis = 1)
# print(f'test1 = \n{test1}')
# test2 = np.sum(np.abs(a), axis = 0)
# print(f'test2 = \n{test2}')
# test3 = np.sum(np.abs(a), axis = 3)
# print(f'test2 = \n{test3}')
print(off_diag)

[6 7 8]


In [13]:
if np.all(diag > off_diag):
  print("Matrix diagonally dominant")
else:
  print("Matrix not diagonally dominant")

Matrix diagonally dominant


In [38]:
x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])
print(x_old)

array([0, 0, 0])

In [39]:
print("Iteration results")
print("k,   x1,      x2,      x3,   epsilon(k)  ")
for k in range(1, 50):
  x1 = (14-3*x2+3*x3)/8
  x2 = (5+2*x1-5*x3)/-8
  x3 = (-8-3*x1-5*x2)/10
  x = np.array([x1, x2, x3])
  # Check if its smaller than treshold
  dx = np.sqrt(np.dot(x-x_old,x-x_old))
  print("%d, %.4f, %.4f, %.4f, %.4f"%(k, x1, x2, x3, dx))
  if dx < epsilon:
    converged = True
    print("Converged!")
    xh = x
    break
  #assign  the latest x
  x_old = x

if not converged:
  print("Not converged, increase the # of iteration")

Iteration results
k,   x1,      x2,      x3,   epsilon(k)  
1, 1.7500, -1.0625, -0.7937, 2.1958
2, 1.8508, -1.5838, -0.5633, 0.5788
3, 2.1327, -1.5103, -0.6847, 0.3156
4, 2.0596, -1.5678, -0.6340, 0.1059
5, 2.1002, -1.5463, -0.6569, 0.0514
6, 2.0835, -1.5565, -0.6468, 0.0220
7, 2.0911, -1.5520, -0.6513, 0.0099
Converged!


In [33]:
xh1 = 8 * x[0] + 3 * x[1] - 3 * x[2]
xh2 = -2 * x[0] - 8 * x[1] + 5 * x[2]
xh3 = 3 * x[0] + 5 * x[1] + 10 * x[2]
print(f'1: {xh1}\n2: {xh2}\n3:{xh3}')


1: 14.02667314511357
2: 4.97758230154049
3:-8.0


In [45]:
# 9x1 + 1x2 - 7x3 = 14
# -2x1 + x2 + 5x3 = 5
# 3x1 - 6x2 + x3 = -8

a = np.array([[9 ,1 ,-7], [-2, 1, 5], [3, -6, 1]])
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all(diag > off_diag):
  print("Matrix diagonally dominant")
else:
  print("Matrix not diagonally dominant")

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

# 9x1 + 1x2 - 7x3 = 14
# -2x1 + x2 + 5x3 = 5
# 3x1 - 6x2 + x3 = -8
print("Iteration results")
print("k,   x1,      x2,      x3,   epsilon(k)  ")
for k in range(1, 50):
  x1 = (14 - x2 + 7 * x3)/9
  x2 = (5 + 2 * x1 - 5 * x3)/1
  x3 = (-8 - 3 * x1 + 6 * x2)/1
  x = np.array([x1, x2, x3])
  # Check if its smaller than treshold
  dx = np.sqrt(np.dot(x-x_old,x-x_old))
  print("%d, %.4f, %.4f, %.4f, %.4f"%(k, x1, x2, x3, dx))
  if dx < epsilon:
    converged = True
    print("Converged!")
    xh = x
    break
  #assign  the latest x
  x_old = x

if not converged:
  print("Not converged, increase the # of iteration")

Matrix not diagonally dominant
Iteration results
k,   x1,      x2,      x3,   epsilon(k)  
1, 1.5556, 8.1111, 36.0000, 36.9352
2, 28.6543, -117.6914, -800.1111, 845.9565
3, -607.6763, 2790.2030, 18556.2469, 19583.9057
4, 14124.1695, -64527.8956, -429547.8820, 453371.8827
5, -326921.4754, 1493901.4593, 9944165.1823, 10495662.7674
6, 7568363.2019, -34584094.5077, -230209664.6520, 242976993.3496
7, -175209282.6729, 800629762.9142, 5329406417.5038, 5624972963.1729
8, 4056135019.2902, -18534762043.9383, -123376977329.5007, 130219410489.2102
9, -93900453249.8407, 429083980152.8221, 2856205240658.4551, 3014609133088.5938
10, 2173816967163.3740, -9933392268960.5273, -66121804515261.2891, 69788890850908.6641
11, -50324359926428.2812, 229960302723454.8750, 1530734896120006.0000, 1615628783427064.5000
12, 1165020441124067.0000, -5323633598351891.0000, -35436862913483552.0000, 37402175819276976.0000
13, -26970489644003664.0000, 123243335279410432.0000, 820371480608473600.0000, 865868923830831232.0

In [46]:
# 9x1 + 10x2 - 7x3 = 14
# -2x1 + 8x2 + 5x3 = 5
# 3x1 + 5x2 + 10x3 = -8

a = np.array([[9 ,1 ,-7], [-2, 1, 5], [3, -6, 1]])
off_diag = np.sum(np.abs(a), axis = 1) - diag

if np.all(diag > off_diag):
  print("Matrix diagonally dominant")
else:
  print("Matrix not diagonally dominant")

x1 = 0
x2 = 0
x3 = 0
epsilon = 0.01
converged = False

x_old = np.array([x1, x2, x3])

# 9x1 + 10x2 - 7x3 = 14
# -2x1 + 8x2 + 5x3 = 5
# 3x1 + 5x2 + 10x3 = -8
print("Iteration results")
print("k,   x1,      x2,      x3,   epsilon(k)  ")
for k in range(1, 50):
  x1 = (14 - 10 * x2 + 7 * x3)/9
  x2 = (5 + 2 * x1 - 5 * x3)/8
  x3 = (-8 - 3 * x1 - 5 * x2)/10
  x = np.array([x1, x2, x3])
  # Check if its smaller than treshold
  dx = np.sqrt(np.dot(x-x_old,x-x_old))
  print("%d, %.4f, %.4f, %.4f, %.4f"%(k, x1, x2, x3, dx))
  if dx < epsilon:
    converged = True
    print("Converged!")
    xh = x
    break
  #assign  the latest x
  x_old = x

if not converged:
  print("Not converged, increase the # of iteration")

Matrix not diagonally dominant
Iteration results
k,   x1,      x2,      x3,   epsilon(k)  
1, 1.5556, 1.0139, -1.7736, 2.5678
2, -0.9505, 1.4959, -1.2628, 2.6026
3, -1.0887, 1.1421, -1.0444, 0.4382
4, -0.5257, 1.1463, -1.2154, 0.5884
5, -0.6635, 1.2188, -1.2103, 0.1557
6, -0.7400, 1.1965, -1.1762, 0.0867
7, -0.6887, 1.1880, -1.1874, 0.0532
8, -0.6879, 1.1951, -1.1912, 0.0081
Converged!


In [48]:
A = np.array([[4, 3, -5],
              [-2, -4, 5],
              [8, 8, 0]])
y = np.array([2, 5, -3])
x = np.linalg.solve(A, y)
print(x)

[ 2.20833333 -2.58333333 -0.18333333]


In [51]:
# a = np.array([[8, 3, -3], [-2, -8, 5], [3, 5, 10]])
a = np.array([[9 ,1 ,-7], [-2, 1, 5], [3, -6, 1]])
# y = np.array([14, 5, -8])
y = np.array([14, 5, -8])
x = np.linalg.solve(a, y)
print(x)

[2.3304721  2.72961373 1.38626609]
